### ISSUE TITLE
Possible regression in f8a6f99

### ISSUE THREAD

**Issue by jeffphilp** [flibitijibibo/MojoShader#2]
In https://github.com/FNA-XNA/FNA/issues/23 a fix was made to support a VS -> PS variable of type COLOR2 to MojoShader in commit https://github.com/flibitijibibo/MojoShader/commit/f7e6b196b935b19c949e2025f778d37a77c86a2d however the next commit https://github.com/flibitijibibo/MojoShader/commit/f8a6f991a3fba48561f7bda89c57db800a8390ad which added a Non-ES fix I think added a regression.  

As the code changed from:

            if (usage_str == NULL)
            {
    #if SUPPORT_PROFILE_GLSLES
                output_line(ctx, "varying highp vec4 io_%i_%i;", usage, index);

    #else
                output_line(ctx, "varying vec4 io_%i_%i;", usage, index);
    #endif
                output_line(ctx, "#define %s io_%i_%i", var, usage, index);
            } // if
to:

            if (usage_str == NULL)
            {
    #if SUPPORT_PROFILE_GLSLES
                if (support_glsles(ctx))
                    output_line(ctx, "varying highp vec4 io_%i_%i;", usage, index);
                else
    #else
                output_line(ctx, "varying vec4 io_%i_%i;", usage, index);
    #endif
                output_line(ctx, "#define %s io_%i_%i", var, usage, index);
            } // if

which results in effectively:

            if (usage_str == NULL)
            {
                if (support_glsles(ctx))
                    output_line(ctx, "varying highp vec4 io_%i_%i;", usage, index);
                else
                    output_line(ctx, "#define %s io_%i_%i", var, usage, index);

so when it generates the GLSL it only outputs the `#define ...` line and not the `io_` variable declaration.  

Perhaps the `#else` should be replaced by an `#endif`

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/MojoShader/commit/d5a811b90107862d2a39533d13f1b75aa6e1690f
